#!/usr/bin/bash

# exit on error
set -e

# print usage
if [ $# -le 1 ]; then
    echo "Usage: generate_isrs.sh <isrs_gen.c> <isrs_gen.inc>"
    exit 1
fi

# vars
ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

# cpu exeptions that push err code onto stack
ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"


# c files
echo "// !!! THIS FILE IS AUTOGENERATED !!!" > "$ISRS_GEN_C"
echo "#include \"idt.h\"" >> "$ISRS_GEN_C"
echo "#include \"gdt.h\"" >> "$ISRS_GEN_C"
echo "" >> "$ISRS_GEN_C"

echo "// provide forward declarations for the assembly entry symbols" >> "$ISRS_GEN_C"
for i in $(eval echo {0..255}); do
    echo "extern void x86_64_ISR_ASM_${i}(void);" >> "$ISRS_GEN_C"
done

echo "" >> "$ISRS_GEN_C"
echo "void x86_64_ISR_InitializeGates(void)" >> "$ISRS_GEN_C"
echo "{" >> "$ISRS_GEN_C"

for i in $(eval echo {0..255}); do
    FLAGS="IDT_FLAG_PRESENT | IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT"
    
    if [ "$i" -eq 128 ]; then
        FLAGS="IDT_FLAG_PRESENT | IDT_FLAG_RING3 | IDT_FLAG_GATE_64BIT_INT"
    fi

    echo "    x86_64_IDT_SetGate(${i}, (uint64_t)x86_64_ISR_ASM_${i}, 0x08, ${FLAGS});" >> "$ISRS_GEN_C"
done

echo "}" >> "$ISRS_GEN_C"





#
# asm file
#
echo "; !!! THIS FILE IS AUTOGENERATED !!!" > "$ISRS_GEN_ASM"
echo "" >> "$ISRS_GEN_ASM"

# Provide simple NASM macros for ISR stubs so the generated file
# can be assembled directly. These macros keep the stack balanced
# and return with `iretq`. For error-code interrupts we pop the
# pushed error code first so `iretq` finds the correct return frame.
echo "%macro ISR_NOERRORCODE 1" >> "$ISRS_GEN_ASM"
echo "    iretq" >> "$ISRS_GEN_ASM"
echo "%endmacro" >> "$ISRS_GEN_ASM"
echo "%macro ISR_ERRORCODE 1" >> "$ISRS_GEN_ASM"
echo "    pop rax    ; remove error code pushed by CPU" >> "$ISRS_GEN_ASM"
echo "    iretq" >> "$ISRS_GEN_ASM"
echo "%endmacro" >> "$ISRS_GEN_ASM"
echo "" >> "$ISRS_GEN_ASM"

for i in $(eval echo {0..255}); do
    echo "global x86_64_ISR_ASM_${i}" >> "$ISRS_GEN_ASM"
    echo "x86_64_ISR_ASM_${i}:" >> "$ISRS_GEN_ASM"
    
    if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        # CPU already pushed error code - pass the vector number.
        echo "    ISR_ERRORCODE ${i}" >> "$ISRS_GEN_ASM"
    else
        # CPU did not push error code - push a dummy 0 so stack layout stays uniform.
        echo "    ISR_NOERRORCODE ${i}" >> "$ISRS_GEN_ASM"
    fi
    echo "" >> "$ISRS_GEN_ASM"
done