#!/usr/bin/bash

# exit on error
set -e

# print usage
if [ $# -le 1 ]; then
    echo "Usage: generate_isrs.sh <isrs_gen.c> <isrs_gen.inc>"
    exit 1
fi

# vars
ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

# CPU Exceptions that natively push an error code onto the stack
ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"

#
# Generate C file
#
echo "// !!! THIS FILE IS AUTOGENERATED !!!" > "$ISRS_GEN_C"
echo "#include \"idt.h\"" >> "$ISRS_GEN_C"
echo "#include \"gdt.h\"" >> "$ISRS_GEN_C"
echo "" >> "$ISRS_GEN_C"

# 64-bit uses the System V AMD64 ABI calling convention by default on Linux/GCC
for i in $(seq 0 255); do
    echo "void __attribute__((sysv_abi)) x86_64_ISR${i}(void);" >> "$ISRS_GEN_C"
done

echo "" >> "$ISRS_GEN_C"
echo "void x86_64_ISR_InitializeGates(void)" >> "$ISRS_GEN_C"
echo "{" >> "$ISRS_GEN_C"

# Flag updated to 64-bit Interrupt Gate (usually 0x8E or defined constant)
for i in $(seq 0 255); do
    echo "    x86_64_IDT_SetGate(${i}, (uint64_t)x86_64_ISR${i}, x86_64_GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);" >> "$ISRS_GEN_C"
done

echo "}" >> "$ISRS_GEN_C"

#
# Generate assembly file
#
echo "; !!! THIS FILE IS AUTOGENERATED !!!" > "$ISRS_GEN_ASM"

for i in $(seq 0 255); do
    if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR_ERRORCODE ${i}" >> "$ISRS_GEN_ASM"
    else
        echo "ISR_NOERRORCODE ${i}" >> "$ISRS_GEN_ASM"
    fi
done
